p8105_hw3_mx2286
================
Mingye
2024-10-15

# Problem 1

Import and clean Dataset

# Problem 1

**load data**

``` r
data("ny_noaa")
```

**Overall**

``` r
str(ny_noaa)
```

    ## tibble [2,595,176 × 7] (S3: tbl_df/tbl/data.frame)
    ##  $ id  : chr [1:2595176] "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" ...
    ##  $ date: Date[1:2595176], format: "2007-11-01" "2007-11-02" ...
    ##  $ prcp: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snow: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snwd: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ tmax: chr [1:2595176] NA NA NA NA ...
    ##  $ tmin: chr [1:2595176] NA NA NA NA ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   id = col_character(),
    ##   ..   date = col_date(format = ""),
    ##   ..   prcp = col_integer(),
    ##   ..   snow = col_integer(),
    ##   ..   snwd = col_integer(),
    ##   ..   tmax = col_character(),
    ##   ..   tmin = col_character()
    ##   .. )

``` r
colMeans(is.na(ny_noaa)) * 100
```

    ##       id     date     prcp     snow     snwd     tmax     tmin 
    ##  0.00000  0.00000  5.61958 14.68960 22.80331 43.71025 43.71264

The dataset consists of 2,595,176 rows and 7 columns. Each row
represents a daily weather observation, and the key variables include:

`id`: A character variable identifying the weather station. `date`: A
date variable representing the date of the observation. `prcp`: An
integer variable indicating precipitation. `snow`: An integer variable
for snowfall measurements. `snwd`: An integer variable for snow depth.
`tmax`: A character variable representing the maximum temperature for
the day. `tmin`: A character variable representing the minimum
temperature.

Several key variables contain many NA values:

`prcp`: 5.62% missing value. `snow`: 14.69% missing value. `snwd`:
22.80% missing value. `tmax`: 43.71% missing value. `tmin`: 43.71%
missing value.

**data cleaning**

``` r
ny_noaa = ny_noaa |> 
  janitor::clean_names() |> 
  mutate(year = as.numeric(format(date, "%Y")),
         month = as.numeric(format(date, "%m")),
         day = as.numeric(format(date, "%d")),
         tmax = as.integer(tmax) / 10,
         tmin = as.integer(tmin) / 10,
         prcp = prcp / 10)

ny_noaa |> 
  group_by(snow) |> 
  summarise(count = n()) |> 
  arrange(desc(count)) |> 
  head(n=5)
```

    ## # A tibble: 5 × 2
    ##    snow   count
    ##   <int>   <int>
    ## 1     0 2008508
    ## 2    NA  381221
    ## 3    25   31022
    ## 4    13   23095
    ## 5    51   18274

The most commonly observed value for snowfall is 0.

**plot 1**

``` r
ny_noaa |> 
  filter(month == '1' | month == '7') |> 
  group_by(year, month) |> 
  summarise(avg_tmax = mean(tmax, na.rm = TRUE), .groups = "drop") |> 
  ungroup() |> 
  ggplot(aes(x = year, y = avg_tmax)) +
  geom_point() +
  facet_wrap(~month) +
  labs(
    title = "Average Max Temp in January and July Across Years",
    x = "Year", y = "Average Max °C"
  ) 
```

![](P8105_hw3_mx2286_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

Temperatures in January show a gradual increase around 0°C over time. In
July, temperatures consistently range between 25-30°C across all years,
without any clear trend. In January, a few data points slightly above or
below 0°C could be considered outliers.

**plot 2**

``` r
tmax_tmin = ny_noaa |> 
  filter(!is.na(tmax) & !is.na(tmin)) |> 
  ggplot(aes(x=tmin, y=tmax)) +
  geom_hex(bins = 30) +
  labs(title = "Hexbin Plot of Tmax vs Tmin", x = "Tmin (°C)", y = "Tmax (°C)")

snow_dist = ny_noaa |> 
  filter(snow > 0 & snow < 100) |> 
  ggplot(aes(x=year, y=snow)) +
  geom_violin() +
  labs(title = "Snowfall Distribution (0 < Snowfall < 100) by Year", x = "Year", y = "Snowfall (mm)")

# Combine the two plots using patchwork
tmax_tmin + snow_dist
```

![](P8105_hw3_mx2286_files/figure-gfm/unnamed-chunk-5-1.png)<!-- --> \#
Problem 2

**data cleaning**

``` r
accel = read.csv("nhanes_accel.csv") |> 
  janitor::clean_names()

covar = read.csv("nhanes_covar.csv", skip = 4) |> 
  janitor::clean_names() |> 
  filter(age >= 21, !is.na(sex), !is.na(age), !is.na(bmi), !is.na(education)) |> 
  mutate(
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    education = factor(education, 
                       levels = c(1, 2, 3), 
                       labels = c("Less than high school", 
                                  "High school equivalent", 
                                  "More than high school"))
  )

mims = inner_join(accel, covar, by = "seqn")
```

**table**

``` r
mims |> 
  group_by(sex, education) |> 
 summarize(count = n(), .groups = "drop") |> 
  pivot_wider(
    names_from = sex,
    values_from = count,
    values_fill = list(count = 0)  # fill missing combinations with 0
  ) |> 
  knitr::kable()
```

| education              | Male | Female |
|:-----------------------|-----:|-------:|
| Less than high school  |   27 |     28 |
| High school equivalent |   35 |     23 |
| More than high school  |   56 |     59 |

``` r
mims |>
  group_by(sex, education) |> 
  ggplot(aes(x = sex, y = age, color = education)) +
  geom_boxplot() +
  labs(
    title = "Age distributions in each education category",
    x = "Sex", y = "Age"
  )
```

![](P8105_hw3_mx2286_files/figure-gfm/unnamed-chunk-7-1.png)<!-- --> The
“Less than high school” group has nearly equal representation of men and
women. In the “High school equivalent” category, men notably outnumber
women. In the “More than high school” group, the gender balance is
relatively even, with a slight majority of women. Additionally, this
group exhibits the widest range in age.

**Total Activity vs. Age by Sex and Education Level**

``` r
mims |> 
  rowwise() |>
  mutate(activity = sum(c_across(starts_with("min")), na.rm = TRUE)) |> 
  ungroup() |> 
  group_by(sex, education) |> 
  ggplot(aes(x = age, y = activity, color = sex)) +
  geom_point(alpha = 0.6, size = 2) +  
  geom_smooth(method = "loess") + 
  facet_wrap(~education) +
  labs(
    title = "Total Activity vs. Age by Sex and Education Level",
    x = "Age", y = "Total Daily Activity"
  ) 
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](P8105_hw3_mx2286_files/figure-gfm/unnamed-chunk-8-1.png)<!-- -->
Higher education levels are linked to more stable activity patterns
throughout life, while lower education levels display greater
variability and a sharper decline in activity, particularly among women.
Gender differences are most evident in the lower education groups, where
women tend to have higher activity levels in early adulthood but
experience a more pronounced decline with age.

**24-Hour Activity Time Courses by Education Level and Sex**

``` r
mims |> 
  pivot_longer(cols = starts_with("min"), 
               names_to = "minute", 
               names_prefix = "min", 
               values_to = "activity") |> 
  mutate(minute = as.numeric(minute))  |> 
  group_by(minute, sex, education) |> 
  summarize(mean_activity = mean(activity, na.rm = TRUE), .groups = "drop") |> 
  ggplot(aes(x = minute, y = mean_activity, color = sex)) +
  geom_point(alpha = 0.2, size = 1.5) +  
  geom_smooth(size = 1.2) +
  facet_wrap(~education, nrow = 3) +
  scale_x_continuous(breaks = seq(0, 1440, by = 120), 
                     labels = function(x) sprintf("%02d:00", x / 60)) +
  labs(title = "24-Hour Activity Time Courses by Education Level and Sex",
       x = "Time of Day (Hours)",  # Clarified label
       y = "Mean Activity Level",
       color = "Sex")
```

    ## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
    ## ℹ Please use `linewidth` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](P8105_hw3_mx2286_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->
While there are minor differences in the timing and intensity of
activity peaks, the overall daily activity pattern is consistent across
all education levels. Activity levels are lower in the early morning and
late night, with noticeable peaks in the late morning and early
afternoon.

Women, particularly in the higher education groups, exhibit higher
activity levels in the morning. Men generally show slightly elevated
activity in the afternoon and evening, especially in the “Less than high
school” group.

Individuals with more education maintain higher and more consistent
activity levels throughout the day, while those with less education tend
to have lower overall activity and experience a decline in activity
earlier in the day.

# Problem 3

**Data Cleaning**

``` r
bike20Jan <- read.csv("Jan 2020 Citi.csv") |> 
  janitor::clean_names() |> 
  mutate(year = 2020, month = "Jan")
bike20July <- read.csv("July 2020 Citi.csv") |> 
  janitor::clean_names() |> 
  mutate(year = 2020, month = "July")
bike24Jan <- read.csv("Jan 2024 Citi.csv") |> 
  janitor::clean_names() |> 
  mutate(year = 2024, month = "Jan")
bike24July <- read.csv("July 2024 Citi.csv") |> 
  janitor::clean_names() |> 
  mutate(year = 2024, month = "July")

citibike = bind_rows(bike20Jan, bike20July, bike24Jan, bike24July) |> 
  mutate(
    weekdays = factor(weekdays, 
                      levels =c("Monday", "Tuesday", "Wednesday", "Thursday", 
                                "Friday", "Saturday", "Sunday")),
    month = factor(month),
    year = factor(year),
   rideable_type = factor(rideable_type)
  )

str(citibike)
```

    ## 'data.frame':    99485 obs. of  9 variables:
    ##  $ ride_id           : chr  "4BE06CB33B037044" "26886E034974493B" "24DC56060EBE6260" "EEDC1053582D02E5" ...
    ##  $ rideable_type     : Factor w/ 2 levels "classic_bike",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ weekdays          : Factor w/ 7 levels "Monday","Tuesday",..: 2 3 5 7 5 7 7 7 4 2 ...
    ##  $ duration          : num  15.33 5.31 9.69 7 2.85 ...
    ##  $ start_station_name: chr  "Columbus Ave & W 95 St" "2 Ave & E 96 St" "Columbia St & Rivington St" "W 84 St & Columbus Ave" ...
    ##  $ end_station_name  : chr  "E 53 St & Madison Ave" "1 Ave & E 110 St" "Grand St & Elizabeth St" "Columbus Ave & W 72 St" ...
    ##  $ member_casual     : chr  "member" "member" "member" "member" ...
    ##  $ year              : Factor w/ 2 levels "2020","2024": 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ month             : Factor w/ 2 levels "Jan","July": 1 1 1 1 1 1 1 1 1 1 ...

The final dataset consists of 99,485 observations and 9 variables,
including `ride_id`, `rideable_type`, `weekdays`, `duration`,
`start_station_name`, `end_station_name`, `member_casual`, `year`,
`month`.\`
